name: ðŸš€ Deploy Client (Swarm)

on:
  push:
    branches: ["main"]

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Client Image 
        run: |
          docker build -t vineeshw1994/swarm-blog-client:${{ github.sha }} .
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker tag vineeshw1994/swarm-blog-client:${{ github.sha }} vineeshw1994/swarm-blog-client:latest
          docker push vineeshw1994/swarm-blog-client:${{ github.sha }}
          docker push vineeshw1994/swarm-blog-client:latest

      - name: SSH Deploy to Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /var/www/swarm
            docker stack deploy -c deploy_all.yml blogstack --with-registry-auth
